import type { PictogramItem } from './types'

export interface DetailedPictogram extends PictogramItem {
  description: string
  audioCue?: string
  hindiText?: string
}

export const EMERGENCY_P0_PICTOGRAMS: DetailedPictogram[] = [
  {
    key: 'chest-pain',
    label: 'Chest Pain',
    hindiText: 'सीने में दर्द',
    icon: 'HeartPulse',
    category: 'emergency',
    color: 'bg-red-50 border-red-500 text-red-700 hover:bg-red-100 active:bg-red-200 dark:bg-red-950/40 dark:border-red-600 dark:text-red-200',
    priority: 'P0',
    description: 'Acute chest tightness, pressure, or heart distress',
  },
  {
    key: 'cant-breathe',
    label: "Can't Breathe",
    hindiText: 'साँस लेने में तकलीफ़',
    icon: 'Wind',
    category: 'emergency',
    color: 'bg-red-50 border-red-500 text-red-700 hover:bg-red-100 active:bg-red-200 dark:bg-red-950/40 dark:border-red-600 dark:text-red-200',
    priority: 'P0',
    description: 'Shortness of breath, choking, or respiratory failure',
  },
  {
    key: 'call-doctor-now',
    label: 'Call Doctor Now',
    hindiText: 'डॉक्टर को तुरंत बुलाएं',
    icon: 'Stethoscope',
    category: 'emergency',
    color: 'bg-red-50 border-red-600 text-red-700 hover:bg-red-100 active:bg-red-200 dark:bg-red-950/40 dark:border-red-500 dark:text-red-200',
    priority: 'P0',
    description: 'Urgent immediate clinical evaluation required',
  },
  {
    key: 'pain-level',
    label: 'Pain Scale (1-10)',
    hindiText: 'दर्द का स्तर (१-१०)',
    icon: 'Activity',
    category: 'pain',
    color: 'bg-amber-50 border-amber-500 text-amber-800 hover:bg-amber-100 active:bg-amber-200 dark:bg-amber-950/40 dark:border-amber-600 dark:text-amber-200',
    priority: 'P0',
    description: 'Indicate severity of pain',
  },
  {
    key: 'i-have-allergy',
    label: 'Severe Allergy',
    hindiText: 'एलर्जी है',
    icon: 'ShieldAlert',
    category: 'allergy',
    color: 'bg-purple-50 border-purple-500 text-purple-800 hover:bg-purple-100 active:bg-purple-200 dark:bg-purple-950/40 dark:border-purple-600 dark:text-purple-200',
    priority: 'P0',
    description: 'Adverse allergic reaction or sensitivity',
  },
  {
    key: 'im-dizzy',
    label: "I'm Dizzy",
    hindiText: 'चक्कर आ रहे हैं',
    icon: 'Sparkles',
    category: 'emergency',
    color: 'bg-amber-50 border-amber-500 text-amber-800 hover:bg-amber-100 active:bg-amber-200 dark:bg-amber-950/40 dark:border-amber-600 dark:text-amber-200',
    priority: 'P0',
    description: 'Lightheadedness, spinning sensation, or loss of balance',
  },
  {
    key: 'water',
    label: 'Need Water',
    hindiText: 'पानी चाहिए',
    icon: 'Droplets',
    category: 'basic',
    color: 'bg-teal-50 border-[#084C5B] text-[#084C5B] hover:bg-teal-100 active:bg-teal-200 dark:bg-teal-950/40 dark:border-teal-500 dark:text-teal-200',
    priority: 'P1',
    description: 'Thirst or need for hydration assistance',
  },
  {
    key: 'toilet',
    label: 'Need Toilet',
    hindiText: 'शौचालय जाना है',
    icon: 'Navigation',
    category: 'basic',
    color: 'bg-teal-50 border-[#084C5B] text-[#084C5B] hover:bg-teal-100 active:bg-teal-200 dark:bg-teal-950/40 dark:border-teal-500 dark:text-teal-200',
    priority: 'P1',
    description: 'Assistance to washroom or bedpan',
  },
  {
    key: 'feel-very-sick',
    label: 'Nausea / Sick',
    hindiText: 'उल्टी या जी घबराना',
    icon: 'AlertTriangle',
    category: 'emergency',
    color: 'bg-amber-50 border-amber-600 text-amber-800 hover:bg-amber-100 active:bg-amber-200 dark:bg-amber-950/40 dark:border-amber-500 dark:text-amber-200',
    priority: 'P0',
    description: 'Feeling ill, upset stomach, or about to vomit',
  },
]

export const ALL_CATEGORY_PICTOGRAMS: Record<string, DetailedPictogram[]> = {
  Emergency: EMERGENCY_P0_PICTOGRAMS,
  'Basic Needs': [
    {
      key: 'water',
      label: 'Water',
      hindiText: 'पानी',
      icon: 'Droplets',
      category: 'basic',
      color: 'bg-teal-50 border-[#084C5B] text-[#084C5B]',
      priority: 'P1',
      description: 'Need water to drink',
    },
    {
      key: 'toilet',
      label: 'Toilet',
      hindiText: 'शौचालय',
      icon: 'Navigation',
      category: 'basic',
      color: 'bg-teal-50 border-[#084C5B] text-[#084C5B]',
      priority: 'P1',
      description: 'Need restroom assistance',
    },
    {
      key: 'blanket',
      label: 'Blanket / Cold',
      hindiText: 'कंबल / ठंड',
      icon: 'Sun',
      category: 'basic',
      color: 'bg-blue-50 border-blue-400 text-blue-800',
      priority: 'P1',
      description: 'Feeling cold, need blanket',
    },
    {
      key: 'hot',
      label: 'Feeling Hot',
      hindiText: 'गर्मी लग रही है',
      icon: 'Flame',
      category: 'basic',
      color: 'bg-orange-50 border-orange-400 text-orange-800',
      priority: 'P1',
      description: 'Overheated or sweating',
    },
    {
      key: 'hungry',
      label: 'Hungry',
      hindiText: 'भूख लगी है',
      icon: 'Utensils',
      category: 'basic',
      color: 'bg-emerald-50 border-emerald-500 text-emerald-800',
      priority: 'P1',
      description: 'Need meal or dietary support',
    },
    {
      key: 'vomit',
      label: 'Vomiting',
      hindiText: 'उल्टी हो रही है',
      icon: 'AlertTriangle',
      category: 'basic',
      color: 'bg-red-50 border-red-400 text-red-700',
      priority: 'P1',
      description: 'Emesis or basin needed',
    },
  ],
  Pain: [
    {
      key: 'head-hurts',
      label: 'Head Pain',
      hindiText: 'सिर दर्द',
      icon: 'Brain',
      category: 'pain',
      color: 'bg-amber-50 border-amber-500 text-amber-800',
      priority: 'P0',
      description: 'Headache or migraine',
    },
    {
      key: 'stomach-hurts',
      label: 'Stomach Pain',
      hindiText: 'पेट दर्द',
      icon: 'CircleDot',
      category: 'pain',
      color: 'bg-amber-50 border-amber-500 text-amber-800',
      priority: 'P0',
      description: 'Abdominal pain',
    },
    {
      key: 'chest-hurts',
      label: 'Chest Ache',
      hindiText: 'छाती में दर्द',
      icon: 'HeartPulse',
      category: 'pain',
      color: 'bg-red-50 border-red-500 text-red-700',
      priority: 'P0',
      description: 'Chest wall pain or ache',
    },
    {
      key: 'back-hurts',
      label: 'Back Pain',
      hindiText: 'पीठ दर्द',
      icon: 'Activity',
      category: 'pain',
      color: 'bg-amber-50 border-amber-500 text-amber-800',
      priority: 'P0',
      description: 'Spinal or muscular back pain',
    },
    {
      key: 'pain-started-now',
      label: 'Pain Started Just Now',
      hindiText: 'दर्द अभी शुरू हुआ',
      icon: 'Clock',
      category: 'pain',
      color: 'bg-red-50 border-red-500 text-red-700',
      priority: 'P0',
      description: 'Sudden acute onset of pain',
    },
  ],
  Allergies: [
    {
      key: 'allergic-penicillin',
      label: 'Penicillin Allergy',
      hindiText: 'पेनिसिलिन एलर्जी',
      icon: 'ShieldAlert',
      category: 'allergy',
      color: 'bg-purple-50 border-purple-500 text-purple-800',
      priority: 'P0',
      description: 'Cannot tolerate penicillin medications',
    },
    {
      key: 'allergic-aspirin',
      label: 'Aspirin Allergy',
      hindiText: 'एस्पिरिन एलर्जी',
      icon: 'ShieldAlert',
      category: 'allergy',
      color: 'bg-purple-50 border-purple-500 text-purple-800',
      priority: 'P0',
      description: 'Cannot take NSAIDs or aspirin',
    },
    {
      key: 'allergic-latex',
      label: 'Latex Allergy',
      hindiText: 'लेटेक्स एलर्जी',
      icon: 'HandMetal',
      category: 'allergy',
      color: 'bg-purple-50 border-purple-500 text-purple-800',
      priority: 'P0',
      description: 'Use non-latex gloves and medical gear',
    },
    {
      key: 'no-known-allergy',
      label: 'No Known Allergies',
      hindiText: 'कोई एलर्जी नहीं',
      icon: 'CheckCircle',
      category: 'allergy',
      color: 'bg-emerald-50 border-emerald-500 text-emerald-800',
      priority: 'P0',
      description: 'No known drug allergies reported',
    },
  ],
}
