import type { ISLClip } from './types'

export const SEED_ISL_CLIPS: ISLClip[] = [
  // Emergency (P0)
  {
    id: 'clip-001',
    key: 'chest-pain',
    label: 'Chest pain',
    aliases: ['my chest hurts', 'heart pain', 'chest ache', 'pain in heart', 'chest pain'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'Chest_Pain_20260912090504.mp4',
    duration_seconds: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-002',
    key: 'cant-breathe',
    label: "Can't breathe",
    aliases: ['breathing problem', 'shortness of breath', 'difficulty breathing', 'hard to breathe', 'choking', 'suffocating', "can't breathe", 'cant breathe', 'cannot breathe'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'Can_t_Breathe_20260913001224.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-003',
    key: 'im-dizzy',
    label: "I'm dizzy",
    aliases: ['feeling dizzy', 'dizziness', 'lightheaded', 'vertigo', 'fainting', "i'm dizzy", 'im dizzy', 'i am dizzy'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'I_m_Dizzy_20260913001318.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-004',
    key: 'feel-very-sick',
    label: 'I feel very sick',
    aliases: ['feeling sick', 'very unwell', 'nauseous', 'ill', 'feel terrible', 'i feel very sick', 'very sick', 'sick'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'I_Feel_very_sick_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-005',
    key: 'call-doctor-now',
    label: 'Call doctor now',
    aliases: ['need doctor', 'get doctor', 'doctor urgent', 'doctor immediately', 'nurse now', 'call doctor', 'call doctor now'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'Call_Doctor_Now_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-006',
    key: 'emergency',
    label: 'Emergency',
    aliases: ['urgent', 'help', 'critical', 'emergency help', 'code blue', 'emergency'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'Help_Me_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-007',
    key: 'help-me',
    label: 'Help me',
    aliases: ['help', 'need help', 'please help', 'assist me', 'urgent help', 'help me'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'Help_Me_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },

  // Pain (P0)
  {
    id: 'clip-008',
    key: 'pain-level',
    label: 'Pain level 1-10',
    aliases: ['rate pain', 'pain scale', 'how much pain', 'pain number', 'severity of pain', 'pain level 1 10', 'pain level'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'Pain_level_1-10_20260913001435.mp4',
    duration_seconds: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-009',
    key: 'head-hurts',
    label: 'My head hurts',
    aliases: ['headache', 'head pain', 'migraine', 'throbbing head', 'my head hurts', 'head hurts'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'My_Head_hurts_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-010',
    key: 'stomach-hurts',
    label: 'My stomach hurts',
    aliases: ['stomach pain', 'belly ache', 'abdominal pain', 'tummy hurts', 'gut pain', 'my stomach hurts', 'stomach ache'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'My_stomach_hurts_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-011',
    key: 'chest-hurts',
    label: 'My chest hurts',
    aliases: ['chest pain', 'pain in chest', 'tight chest', 'my chest hurts'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'My_chest_hurts_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-012',
    key: 'back-hurts',
    label: 'My back hurts',
    aliases: ['back pain', 'backache', 'lower back pain', 'spine pain', 'my back hurts'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'My_back_hurts_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-013',
    key: 'pain-started-now',
    label: 'Pain started now',
    aliases: ['sudden pain', 'pain just started', 'new pain', 'just began', 'pain started now'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'Pain_started_now_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },

  // Allergies (P0)
  {
    id: 'clip-014',
    key: 'i-have-allergy',
    label: 'I have allergy',
    aliases: ['allergic', 'allergy', 'allergic reaction', 'severe allergy', 'i have allergy'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'I_have_allergy_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-015',
    key: 'allergic-penicillin',
    label: 'Allergic to penicillin',
    aliases: ['penicillin allergy', 'cannot take penicillin', 'no penicillin', 'allergic to penicillin', 'penicillin'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'allergic_to_penicillin_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-016',
    key: 'allergic-aspirin',
    label: 'Allergic to aspirin',
    aliases: ['aspirin allergy', 'cannot take aspirin', 'no aspirin', 'allergic to aspirin', 'aspirin'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'Allergic_to_aspirin_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-017',
    key: 'allergic-latex',
    label: 'Allergic to latex',
    aliases: ['latex allergy', 'cannot use latex', 'no latex gloves', 'allergic to latex', 'latex'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'allergic_to_latex_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-018',
    key: 'no-known-allergy',
    label: 'No known allergy',
    aliases: ['no allergies', 'not allergic', 'allergy free', 'nkda', 'no known allergy', 'no known allergies'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'No_known_allergy_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },

  // Basic needs (P1)
  {
    id: 'clip-019',
    key: 'water',
    label: 'Water',
    aliases: ['thirsty', 'need water', 'drink', 'glass of water', 'water'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Water_20260913001437.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-020',
    key: 'toilet',
    label: 'Toilet',
    aliases: ['bathroom', 'restroom', 'need toilet', 'washroom', 'urinate', 'toilet', 'loo'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Toilet_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-021',
    key: 'cold',
    label: 'Cold',
    aliases: ['feeling cold', 'chilly', 'freezing', 'shivering', 'cold'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Cold_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-022',
    key: 'hot',
    label: 'Hot',
    aliases: ['feeling hot', 'warm', 'overheated', 'sweating', 'hot'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Hot_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-023',
    key: 'blanket',
    label: 'Blanket',
    aliases: ['need blanket', 'cover', 'sheet', 'warm cover', 'blanket'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Blanket_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-024',
    key: 'hungry',
    label: 'Hungry',
    aliases: ['need food', 'want to eat', 'starving', 'food', 'hungry'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Hungry_20260913001435.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-025',
    key: 'nausea',
    label: 'Nausea',
    aliases: ['feeling nauseous', 'sick to stomach', 'queasy', 'nausea'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Nausea_20260913001435.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-026',
    key: 'vomit',
    label: 'Vomit',
    aliases: ['throwing up', 'vomiting', 'being sick', 'puke', 'vomit'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'Vomit_20260913001435.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },

  // Medical history (P1)
  {
    id: 'clip-027',
    key: 'diabetic',
    label: 'Diabetic',
    aliases: ['diabetes', 'sugar problem', 'blood sugar', 'insulin', 'diabetic'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'Diabetic_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-028',
    key: 'heart-condition',
    label: 'Heart condition',
    aliases: ['heart problem', 'cardiac', 'heart disease', 'stent', 'heart condition'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'Heart_condition_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-029',
    key: 'high-blood-pressure',
    label: 'High blood pressure',
    aliases: ['hypertension', 'BP high', 'blood pressure problem', 'high blood pressure', 'bp'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'high_blood_pressure_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-030',
    key: 'pregnant',
    label: 'Pregnant',
    aliases: ['pregnancy', 'expecting', 'with child', 'baby', 'pregnant'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'Pregnant_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-031',
    key: 'surgery-before',
    label: 'Surgery before',
    aliases: ['previous surgery', 'had operation', 'past surgery', 'prior operation', 'surgery before', 'surgery'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'Before_Surgery_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-032',
    key: 'blood-type',
    label: 'Blood type',
    aliases: ['blood group', 'what blood type', 'A B O', 'Rh positive', 'blood type'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'Blood_type_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },

  // Doctor to patient (P1)
  {
    id: 'clip-033',
    key: 'you-are-safe',
    label: 'You are safe',
    aliases: ['safe', "don't worry", "you're okay", 'everything is fine', 'you are safe'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'You_are_safe_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-034',
    key: 'we-are-helping',
    label: 'We are helping you',
    aliases: ['helping', 'taking care', 'treating you', 'assisting', 'we are helping you', 'we are helping'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'We_are_helping_you_20260913001436.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-035',
    key: 'do-you-understand',
    label: 'Do you understand?',
    aliases: ['understand', 'clear', 'got it', 'comprehend', 'do you understand', 'understand?'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'Do_you_understand__20260913002754.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-036',
    key: 'take-medicine',
    label: 'Take this medicine',
    aliases: ['medicine', 'tablet', 'pill', 'medication', 'take this', 'take this medicine', 'take medicine', 'take pill', 'take your medicine'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'Take_this_medicine_20260913001437.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-037',
    key: 'stay-still',
    label: 'Stay still',
    aliases: ["don't move", 'remain still', 'hold still', 'be still', 'stay still'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'Stay_Still_20260913001436.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-038',
    key: 'relax',
    label: 'Relax',
    aliases: ['calm down', 'take it easy', 'breathe', 'stay calm', 'relax', 'relax / breathe', 'relax breathe', 'breathe / relax', 'take a breath', 'deep breath'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'Relax_20260913001435.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-039',
    key: 'good',
    label: 'Good',
    aliases: ['well done', "that's good", 'great', 'okay good', 'good', 'fine'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'Good_20260913001435.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },

  // Consent (P2)
  {
    id: 'clip-040',
    key: 'do-you-agree',
    label: 'Do you agree?',
    aliases: ['agree', 'consent', 'approval', 'permission', 'is that okay', 'do you agree', 'do you agree?'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'Do_you_agree__20260913002935.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-041',
    key: 'sign-here',
    label: 'Sign here',
    aliases: ['signature', 'sign this', 'put your sign', 'autograph', 'sign here'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'Sign_here_20260913001435.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-042',
    key: 'need-to-do-test',
    label: 'We need to do a test',
    aliases: ['test', 'examination', 'check', 'diagnostic', 'lab test', 'we need to do a test', 'need to do a test', 'do a test', 'need a test'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'We_need_to_do_a_test_20260913001435.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-043',
    key: 'this-will-help',
    label: 'This will help you',
    aliases: ['this helps', 'beneficial', 'for your benefit', 'treatment', 'this will help you', 'this will help'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'This_will_help_you__20260913001435.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-044',
    key: 'family-here',
    label: 'Do you have family here?',
    aliases: ['family', 'relative', 'someone with you', 'companion', 'guardian', 'do you have family here', 'family here'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'Do_you_have_a_family_here_20260913001435.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
]
