import type { ISLClip } from './types'

export const SEED_ISL_CLIPS: ISLClip[] = [
  // Emergency (P0)
  {
    id: 'clip-001',
    key: 'chest-pain',
    label: 'Chest pain',
    aliases: ['my chest hurts', 'heart pain', 'chest ache', 'pain in heart'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'chest-pain.mp4',
    duration_seconds: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-002',
    key: 'cant-breathe',
    label: "Can't breathe",
    aliases: ['breathing problem', 'shortness of breath', 'difficulty breathing', 'hard to breathe', 'choking', 'suffocating'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'cant-breathe.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-003',
    key: 'im-dizzy',
    label: "I'm dizzy",
    aliases: ['feeling dizzy', 'dizziness', 'lightheaded', 'vertigo', 'fainting'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'im-dizzy.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-004',
    key: 'feel-very-sick',
    label: 'I feel very sick',
    aliases: ['feeling sick', 'very unwell', 'nauseous', 'ill', 'feel terrible'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'feel-very-sick.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-005',
    key: 'call-doctor-now',
    label: 'Call doctor now',
    aliases: ['need doctor', 'get doctor', 'doctor urgent', 'doctor immediately', 'nurse now'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'call-doctor-now.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-006',
    key: 'emergency',
    label: 'Emergency',
    aliases: ['urgent', 'help', 'critical', 'emergency help', 'code blue'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'emergency.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-007',
    key: 'help-me',
    label: 'Help me',
    aliases: ['help', 'need help', 'please help', 'assist me', 'urgent help'],
    category: 'Emergency',
    priority: 'P0',
    storage_path: 'help-me.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },

  // Pain (P0)
  {
    id: 'clip-008',
    key: 'pain-level',
    label: 'Pain level 1-10',
    aliases: ['rate pain', 'pain scale', 'how much pain', 'pain number', 'severity of pain'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'pain-level.mp4',
    duration_seconds: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-009',
    key: 'head-hurts',
    label: 'My head hurts',
    aliases: ['headache', 'head pain', 'migraine', 'throbbing head'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'head-hurts.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-010',
    key: 'stomach-hurts',
    label: 'My stomach hurts',
    aliases: ['stomach pain', 'belly ache', 'abdominal pain', 'tummy hurts', 'gut pain'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'stomach-hurts.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-011',
    key: 'chest-hurts',
    label: 'My chest hurts',
    aliases: ['chest pain', 'pain in chest', 'tight chest'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'chest-hurts.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-012',
    key: 'back-hurts',
    label: 'My back hurts',
    aliases: ['back pain', 'backache', 'lower back pain', 'spine pain'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'back-hurts.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-013',
    key: 'pain-started-now',
    label: 'Pain started now',
    aliases: ['sudden pain', 'pain just started', 'new pain', 'just began'],
    category: 'Pain',
    priority: 'P0',
    storage_path: 'pain-started-now.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },

  // Allergies (P0)
  {
    id: 'clip-014',
    key: 'i-have-allergy',
    label: 'I have allergy',
    aliases: ['allergic', 'allergy', 'allergic reaction', 'severe allergy'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'i-have-allergy.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-015',
    key: 'allergic-penicillin',
    label: 'Allergic to penicillin',
    aliases: ['penicillin allergy', 'cannot take penicillin', 'no penicillin'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'allergic-penicillin.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-016',
    key: 'allergic-aspirin',
    label: 'Allergic to aspirin',
    aliases: ['aspirin allergy', 'cannot take aspirin', 'no aspirin'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'allergic-aspirin.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-017',
    key: 'allergic-latex',
    label: 'Allergic to latex',
    aliases: ['latex allergy', 'cannot use latex', 'no latex gloves'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'allergic-latex.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-018',
    key: 'no-known-allergy',
    label: 'No known allergy',
    aliases: ['no allergies', 'not allergic', 'allergy free', 'nkda'],
    category: 'Allergies',
    priority: 'P0',
    storage_path: 'no-known-allergy.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },

  // Basic needs (P1)
  {
    id: 'clip-019',
    key: 'water',
    label: 'Water',
    aliases: ['thirsty', 'need water', 'drink', 'glass of water'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'water.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-020',
    key: 'toilet',
    label: 'Toilet',
    aliases: ['bathroom', 'restroom', 'need toilet', 'washroom', 'urinate'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'toilet.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-021',
    key: 'cold',
    label: 'Cold',
    aliases: ['feeling cold', 'chilly', 'freezing', 'shivering'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'cold.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-022',
    key: 'hot',
    label: 'Hot',
    aliases: ['feeling hot', 'warm', 'overheated', 'sweating'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'hot.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-023',
    key: 'blanket',
    label: 'Blanket',
    aliases: ['need blanket', 'cover', 'sheet', 'warm cover'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'blanket.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-024',
    key: 'hungry',
    label: 'Hungry',
    aliases: ['need food', 'want to eat', 'starving', 'food'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'hungry.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-025',
    key: 'nausea',
    label: 'Nausea',
    aliases: ['feeling nauseous', 'sick to stomach', 'queasy'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'nausea.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-026',
    key: 'vomit',
    label: 'Vomit',
    aliases: ['throwing up', 'vomiting', 'being sick', 'puke'],
    category: 'Basic needs',
    priority: 'P1',
    storage_path: 'vomit.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },

  // Medical history (P1)
  {
    id: 'clip-027',
    key: 'diabetic',
    label: 'Diabetic',
    aliases: ['diabetes', 'sugar problem', 'blood sugar', 'insulin'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'diabetic.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-028',
    key: 'heart-condition',
    label: 'Heart condition',
    aliases: ['heart problem', 'cardiac', 'heart disease', 'stent'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'heart-condition.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-029',
    key: 'high-blood-pressure',
    label: 'High blood pressure',
    aliases: ['hypertension', 'BP high', 'blood pressure problem'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'high-blood-pressure.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-030',
    key: 'pregnant',
    label: 'Pregnant',
    aliases: ['pregnancy', 'expecting', 'with child', 'baby'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'pregnant.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-031',
    key: 'surgery-before',
    label: 'Surgery before',
    aliases: ['previous surgery', 'had operation', 'past surgery', 'prior operation'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'surgery-before.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-032',
    key: 'blood-type',
    label: 'Blood type',
    aliases: ['blood group', 'what blood type', 'A B O', 'Rh positive'],
    category: 'Medical history',
    priority: 'P1',
    storage_path: 'blood-type.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },

  // Doctor to patient (P1)
  {
    id: 'clip-033',
    key: 'you-are-safe',
    label: 'You are safe',
    aliases: ['safe', "don't worry", "you're okay", 'everything is fine'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'you-are-safe.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-034',
    key: 'we-are-helping',
    label: 'We are helping you',
    aliases: ['helping', 'taking care', 'treating you', 'assisting'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'we-are-helping.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-035',
    key: 'do-you-understand',
    label: 'Do you understand?',
    aliases: ['understand', 'clear', 'got it', 'comprehend'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'do-you-understand.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-036',
    key: 'take-medicine',
    label: 'Take this medicine',
    aliases: ['medicine', 'tablet', 'pill', 'medication', 'take this'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'take-medicine.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-037',
    key: 'stay-still',
    label: 'Stay still',
    aliases: ["don't move", 'remain still', 'hold still', 'be still'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'stay-still.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-038',
    key: 'relax',
    label: 'Relax',
    aliases: ['calm down', 'take it easy', 'breathe', 'stay calm'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'relax.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-039',
    key: 'good',
    label: 'Good',
    aliases: ['well done', "that's good", 'great', 'okay good'],
    category: 'Doctor to patient',
    priority: 'P1',
    storage_path: 'good.mp4',
    duration_seconds: 10,
    created_at: new Date().toISOString(),
  },

  // Consent (P2)
  {
    id: 'clip-040',
    key: 'do-you-agree',
    label: 'Do you agree?',
    aliases: ['agree', 'consent', 'approval', 'permission', 'is that okay'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'do-you-agree.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-041',
    key: 'sign-here',
    label: 'Sign here',
    aliases: ['signature', 'sign this', 'put your sign', 'autograph'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'sign-here.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-042',
    key: 'need-to-do-test',
    label: 'We need to do a test',
    aliases: ['test', 'examination', 'check', 'diagnostic', 'lab test'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'need-to-do-test.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-043',
    key: 'this-will-help',
    label: 'This will help you',
    aliases: ['this helps', 'beneficial', 'for your benefit', 'treatment'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'this-will-help.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
  {
    id: 'clip-044',
    key: 'family-here',
    label: 'Do you have family here?',
    aliases: ['family', 'relative', 'someone with you', 'companion', 'guardian'],
    category: 'Consent',
    priority: 'P2',
    storage_path: 'family-here.mp4',
    duration_seconds: 15,
    created_at: new Date().toISOString(),
  },
]
